name: gym-duckietown
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.6
    - pytorch=0.3
    - torchvision
    - pyglet
    - pyzmq
    - numpy
    - opencv-python
    - scikit-image
    - pip:
        - gym
